src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

#[ORM\Entity(repositoryClass: EventRepository::class)]
#[Vich\Uploadable]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;


    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Date_fin = null;

    #[ORM\ManyToOne(inversedBy: 'events')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Department $Id_depart = null;

    #[ORM\OneToMany(mappedBy: 'Id_event', targetEntity: Devis::class, orphanRemoval: true)]
    private Collection $devis;

    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'User_Event')]
    private Collection $users;

    #[ORM\OneToMany(mappedBy: 'Id_event', targetEntity: Options::class, orphanRemoval: true)]
    private Collection $options;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $lieu = null;

    #[Vich\UploadableField(mapping: 'events', fileNameProperty: 'image')]
    private ?File $imageFile = null;

    #[ORM\Column(type: 'string', nullable: false, length: 255)]
    private ?string $image = null;

    #[ORM\Column(length: 255)]
    private ?string $entree = null;

    #[ORM\Column(length: 255)]
    private ?string $plat = null;

    #[ORM\Column(length: 255)]
    private ?string $dessert = null;

    public function __construct()
    {
        $this->devis = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }


    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->Date_debut;
    }

    public function setDateDebut(\DateTimeInterface $Date_debut): self
    {
        $this->Date_debut = $Date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->Date_fin;
    }

    public function setDateFin(\DateTimeInterface $Date_fin): self
    {
        $this->Date_fin = $Date_fin;

        return $this;
    }

    public function getIdDepart(): ?Department
    {
        return $this->Id_depart;
    }

    public function setIdDepart(?Department $Id_depart): self
    {
        $this->Id_depart = $Id_depart;

        return $this;
    }

    /**
     * @return Collection<int, Devis>
     */
    public function getDevis(): Collection
    {
        return $this->devis;
    }

    public function addDevi(Devis $devi): self
    {
        if (!$this->devis->contains($devi)) {
            $this->devis->add($devi);
            $devi->setIdEvent($this);
        }

        return $this;
    }

    public function removeDevi(Devis $devi): self
    {
        if ($this->devis->removeElement($devi)) {
            // set the owning side to null (unless already changed)
            if ($devi->getIdEvent() === $this) {
                $devi->setIdEvent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addUserEvent($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeUserEvent($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Options>
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Options $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options->add($option);
            $option->setIdEvent($this);
        }

        return $this;
    }

    public function removeOption(Options $option): self
    {
        if ($this->options->removeElement($option)) {
            // set the owning side to null (unless already changed)
            if ($option->getIdEvent() === $this) {
                $option->setIdEvent(null);
            }
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile): self
    {
        $this->imageFile = $imageFile;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getEntree(): ?string
    {
        return $this->entree;
    }

    public function setEntree(string $entree): self
    {
        $this->entree = $entree;

        return $this;
    }

    public function getPlat(): ?string
    {
        return $this->plat;
    }

    public function setPlat(string $plat): self
    {
        $this->plat = $plat;

        return $this;
    }

    public function getDessert(): ?string
    {
        return $this->dessert;
    }

    public function setDessert(string $dessert): self
    {
        $this->dessert = $dessert;

        return $this;
    }

    public function __toString()
    {
        return $this->Name; // Remplacer champ par une propriété "string" de l'entité
    }
}

src/Entity/School.php
<?php

namespace App\Entity;

use App\Repository\SchoolRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SchoolRepository::class)]
class School
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;

    #[ORM\Column(length: 255)]
    private ?string $Address = null;

    #[ORM\Column(length: 255)]
    private ?string $Mail = null;

    #[ORM\Column(length: 255)]
    private ?string $Phone = null;

    #[ORM\OneToMany(mappedBy: 'Id_school', targetEntity: Department::class, orphanRemoval: true)]
    private Collection $departments;

    public function __construct()
    {
        $this->departments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->Mail;
    }

    public function setMail(string $Mail): self
    {
        $this->Mail = $Mail;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->Phone;
    }

    public function setPhone(string $Phone): self
    {
        $this->Phone = $Phone;

        return $this;
    }

    /**
     * @return Collection<int, Department>
     */
    public function getDepartments(): Collection
    {
        return $this->departments;
    }

    public function addDepartment(Department $department): self
    {
        if (!$this->departments->contains($department)) {
            $this->departments->add($department);
            $department->setIdSchool($this);
        }

        return $this;
    }

    public function removeDepartment(Department $department): self
    {
        if ($this->departments->removeElement($department)) {
            // set the owning side to null (unless already changed)
            if ($department->getIdSchool() === $this) {
                $department->setIdSchool(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->Name; // Remplacer champ par une propriété "string" de l'entité
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;

use Symfony\Component\Form\Extension\Core\Type\DateType;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Name', null, [
                'label' => 'Nom de l\'événement',
            ])
            ->add('Date_debut', null, [
                'label' => 'Date de début',
            ], DateType::class)
            ->add('Date_fin', null, [
                'label' => 'Date de fin',
            ], DateType::class)
            ->add('description', null, [
                'label' => 'Description  ',
            ])
            ->add('lieu', null, [
                'label' => 'Lieu',
            ])
            // ->add('image', null, [
            //     'required' => false,
            //     'label' => 'Nom de l\'image',
            //     'empty_data' => ''
            // ])
            ->add('imageFile', fileType::class, [
                'required' => false,
                'label' => 'Sélection image',
                'empty_data' => ''
            ])
            ->add('Id_depart')
            ->add('entree')
            ->add('plat')
            ->add('dessert', null, [
                'label' => 'dessert',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Department;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Event;
use App\Entity\School;
use App\Form\EventType;
use App\Repository\EventRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/event')]
class EventController extends AbstractController
{

    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    #[Route('/', name: 'app_event_index', methods: ['GET'])]
    public function index(EventRepository $eventRepository): Response
    {
        return $this->render('event/index.html.twig', [
            'events' => $eventRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_event_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EventRepository $eventRepository): Response
    {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $eventRepository->save($event, true);

            return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('event/new.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_event_show', methods: ['GET'])]
    public function show(Event $event, EntityManagerInterface $entityManager): Response
    {
        $departId = $event->getIdDepart();
        $depart = $entityManager->getRepository(Department::class)->find($departId);
        $schoolId = $depart->getIdSchool();
        $school = $entityManager->getRepository(School::class)->find($schoolId);
        return $this->render('event/show.html.twig', [
            'event' => $event,
            'department' => $depart,
            'school' => $school
        ]);
    }

    #[Route('/{id}/edit', name: 'app_event_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Event $event, EventRepository $eventRepository): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $eventRepository->save($event, true);

            return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('event/edit.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_event_delete', methods: ['POST'])]
    public function delete(Request $request, Event $event, EventRepository $eventRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $event->getId(), $request->request->get('_token'))) {
            $eventRepository->remove($event, true);
        }
        //return to home
        return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}/register', name: 'app_event_register', methods: ['POST'])]
    public function eventRegister(Request $request, Event $event): Response
    {
        $user = $this->getUser();
        $user->addUserEvent($event);
        $this->entityManager->flush();

        return $this->redirectToRoute('app_event_show', ['id' => $event->getId()]);
    }
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('app_event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn_delete_user"><img src="{{ asset('assets/img/user.svg') }}" class="delete_icon" alt="Delete"</button>
</form>

templates/event/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn_create">{{ button_label|default('Créer') }}</button>
{{ form_end(form) }}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Event{% endblock %}
{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('assets/styles/styles.css') }}">
	<link rel="stylesheet" href="{{ asset('assets/styles/stylesDetailsEvent.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/styles/stylesFooter.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/styles/stylesCreate.css') }}">
{% endblock %}
{% block body %}
    <h1>Edit Event</h1>

    {{ include('event/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="backEdit" href="{{ path('app_home') }}">back to list</a>

    {{ include('event/_delete_form.html.twig') }}
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event index{% endblock %}

{% block body %}
    <h1>Event index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>Description</th>
                <th>Lieu</th>
                <th>Image</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for event in events %}
            <tr>
                <td>{{ event.id }}</td>
                <td>{{ event.Name }}</td>
                <td>{{ event.DateDebut ? event.DateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ event.DateFin ? event.DateFin|date('Y-m-d') : '' }}</td>
                <td>{{ event.description }}</td>
                <td>{{ event.lieu }}</td>
                <td>{{ event.image }}</td>
                <td>
                    <a href="{{ path('app_event_show', {'id': event.id}) }}">show</a>
                    <a href="{{ path('app_event_edit', {'id': event.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_event_new') }}">Create new</a>
{% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}


{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('assets/styles/styles.css') }}">
	<link rel="stylesheet" href="{{ asset('assets/styles/stylesDetailsEvent.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/styles/stylesFooter.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/styles/stylesCreate.css') }}">
{% endblock %}

{% block title %}Créer un evennement{% endblock %}

{% block body %}
        <h1 class="create_envent_title">Créer un évènement</h1>
        <div class="new_event_div">
            {{ include('event/_form.html.twig') }}
        </div>
{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('assets/styles/styles.css') }}">
	<link rel="stylesheet" href="{{ asset('assets/styles/stylesDetailsEvent.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/styles/stylesFooter.css') }}">
{% endblock %}


{% block title %}Détails de l'événement{% endblock %}

{% block body %}

    <div class="navigation_page">
        <a href="{{ path('app_home') }}">Accueil</a> > <a>{{event.Name}} </a>{#<a href="{{ path('event_show', {'id': event.id}) }}">{{ event.title }}</a> #}
    </div>

<div class="header_event">
            <div class="container_header">
                <div class="header_event__title">
                    <h2>{{event.Name}}</h2>
                </div>
                <div class="detail_header">
                    <div class="header_event__date">
                        <h2>Début : {{ event.DateDebut ? event.DateDebut|date('Y-m-d') : '' }}</h2>
                    </div><div class="header_event__date">
                        <h2>Fin : {{ event.DateFin ? event.DateFin|date('Y-m-d') : '' }}</h2>
                    </div>
                </div>               
            </div>

</div>
{# <a href="{{ path('app_devis_maker') }}">Devis<i class="fa-solid fa-arrow-right"></i></a> #}

<div class="detail_event">
    <div class="description">
        <h2>Description</h2>
        <p>{{ event.description }}</p>
        </div>
    <div class="menu">
        <h2>Menu</h2>
        <p>Entrée : {{ event.entree }}</p>
        <p>Plat : {{ event.plat }}</p>
        <p>Dessert : {{ event.dessert }}</p>
    </div>
    <div class="lieu">
        <h2>Département</h2>
        <p>{{ department.name }}</p>
    </div>
    <div class="lieu">
        <h2>Ecole</h2>
        <p>{{ school.name }}</p>
        <p>{{ school.address }}</p>
        <p>{{ school.mail }}</p>
        <p>{{ school.phone }}</p>
    </div>
    {% if app.user %}
        <form method="POST" action="{{ path('app_event_register', {'id': event.id}) }}">
            <input type="hidden" name="user" id="idUser" value="{{ app.user.id }}"></input>
            <input type="hidden" name="event" id="idEvent" value="{{ event.id }}"></input>
            <button type="submit" class="btn moreInfoButton_button">S'inscrire à l'évenement</button>
        </form>   
    {% else %}
        <h3>Connectez-vous</h3>
        <a type="submit" class="btn moreInfoButton" disabled>Créer un compte</a>
    {% endif %}
    {% if is_granted('ROLE_ADMIN') == true %}
        {# <a href="{{path('_delete_form.html.twig', {'id': event.id})}}" class="moreInfoButton_button_delete" >Supprimer l'évenement</a>
    <input type="text"> #}

        {{ include('event/_delete_form.html.twig') }}

    {% endif %}
</div>
{% endblock %}