src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $Firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $Lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $Telephone = null;

    #[ORM\OneToMany(mappedBy: 'Id_user', targetEntity: Devis::class, orphanRemoval: true)]
    private Collection $devis;

    #[ORM\ManyToMany(targetEntity: Event::class, inversedBy: 'users')]
    private Collection $User_Event;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    public function __construct()
    {
        $this->devis = new ArrayCollection();
        $this->User_Event = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->Firstname;
    }

    public function setFirstname(string $Firstname): self
    {
        $this->Firstname = $Firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->Lastname;
    }

    public function setLastname(string $Lastname): self
    {
        $this->Lastname = $Lastname;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->Telephone;
    }

    public function setTelephone(string $Telephone): self
    {
        $this->Telephone = $Telephone;

        return $this;
    }

    /**
     * @return Collection<int, Devis>
     */
    public function getDevis(): Collection
    {
        return $this->devis;
    }

    public function addDevi(Devis $devi): self
    {
        if (!$this->devis->contains($devi)) {
            $this->devis->add($devi);
            $devi->setIdUser($this);
        }

        return $this;
    }

    public function removeDevi(Devis $devi): self
    {
        if ($this->devis->removeElement($devi)) {
            // set the owning side to null (unless already changed)
            if ($devi->getIdUser() === $this) {
                $devi->setIdUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Event>
     */
    public function getUserEvent(): Collection
    {
        return $this->User_Event;
    }

    public function addUserEvent(Event $event): self
    {
        if (!$this->User_Event->contains($event)) {
            $this->User_Event[] = $event;
            $event->addUser($this);
        }

        return $this;
    }

    public function removeUserEvent(Event $userEvent): self
    {
        $this->User_Event->removeElement($userEvent);

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %} ChallengeWebIut {% endblock %}
		</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">		{# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
		{% block stylesheets %}
			<link rel="stylesheet" href="{{ asset('assets/styles/styles.css') }}">
			<link rel="stylesheet" href="{{ asset('assets/styles/userStyle.css') }}">
			<link rel="stylesheet" href="{{ asset('assets/styles/stylesfooter.css') }}">
			<link rel="stylesheet" href="{{ asset('assets/styles/stylesdevis.css') }}">
		{% endblock %}

	</head>
	
	<body>
		<!-- Navbar -->
		<nav class="nav">
			<a href="{{ path('app_home') }}"><img  src="{{ asset('assets/img/logo_iut.png') }}" alt="logo des iut" class="logo_nav"></a>
			<div class="link_nav">
				<ul>
					{% if app.user %}
						<li >
							<p>Bienvenue <a class="btn_nav_user" href="{{ path('app_account') }}">{{app.user.firstname}}</a>!</p>
						</li>
						<li>
							<a href="{{ path('app_logout') }}"><i class="fa-solid fa-user-minus"></i><span> Déconnexion</span></a>
						</li>
					{% else %}
						<li>
                			<a href="{{ path('app_login') }}"><i class="fa-solid fa-user"></i><span>Se connecter</span></a>
              			</li>
						<li>
							<a href="{{ path('app_register') }}"><i class="fa-solid fa-user-plus"></i><span>S'inscrire</span></a>
						</li>
					{% endif %}
				</ul>
			</div>
				
		</nav><!-- Fin de la navbar -->		
	

{% block body %}
{% endblock %}

<footer>

	<div class="footer">
		<a href="{{ path('app_home') }}"><img  src="{{ asset('assets/img/logo_iut.png') }}" alt="logo des iut" class="logo_nav"></a>
		<div class="listtext">
			<a href="{{ path('app_home') }}">Accueil</a>
			{% if app.user %}
			<a href="{{ path('app_account') }}">Mon Compte</a>
			{% endif %}
			<a href="https://www.iut.fr">IUT INFO</a>
			<a href="{{ path('app_mention') }}">Mentions légales</a>
		</div>
		<div class="social_contact">
			<div class="social-icons">
				<a href="https://www.instagram.com"><i class="fab fa-instagram"></i></a>
				<a href="https://www.facebook.com"><i class="fab fa-facebook"></i></a>
				<a href="https://www.linkedin.com"><i class="fab fa-linkedin"></i></a>
				<a href="https://twitter.com"><i class="fab fa-twitter"></i></a>
			</div>
			<a href="mailto:challenge@antonio.net" class="btn_contact">Contactez-nous</a>
		</div>
		
	</div>
</footer>

</body>
</html>

templates/devisbase.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %} ChallengeWebIut {% endblock %}
		</title>
		<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">		{# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
		{% block stylesheets %}
			<link rel="stylesheet" href="{{ asset('assets/styles/styles.css') }}">
			<link rel="stylesheet" href="{{ asset('assets/styles/userStyle.css') }}">
			<link rel="stylesheet" href="{{ asset('assets/styles/stylesfooter.css') }}">
			<link rel="stylesheet" href="{{ asset('assets/styles/stylesdevis.css') }}">
		{% endblock %}
<style>
            /** Define the margins of your page **/
            @page {
                margin: 100px 25px;
            }



            footer {
                position: fixed; 
                bottom: -6000000000000000px; 
                size: 0.8px; 

                /** Extra personal styles **/
                background-color: #03a9f4;
                color: white;
                text-align: center;
                line-height: 35px;
            }
        </style>
	</head>
	
	<body>
		<!-- Navbar -->
		<		
	

{% block body %}
{% block content %}
{% endblock %}
{% endblock %}

<footer>

     <div class="container">
		<a href="{{ path('app_home') }}"><img  src="{{ asset('assets/img/logo_iut.png') }}" alt="logo des iut" class="logo_nav"></a>
		<div class="listtext">
			<a href="{{ path('app_home') }}">Accueil</a>
			{% if app.user %}
			<a href="{{ path('app_account') }}">Mon Compte</a>
			{% endif %}
			<a href="https://www.iut.fr">IUT INFO</a>
			<a href="{{ path('app_mention') }}">Mentions légales</a>
		</div>
		<div class="social_contact">
			<div class="social-icons">
				<a href="https://www.instagram.com"><i class="fab fa-instagram"></i></a>
				<a href="https://www.facebook.com"><i class="fab fa-facebook"></i></a>
				<a href="https://www.linkedin.com"><i class="fab fa-linkedin"></i></a>
				<a href="https://twitter.com"><i class="fab fa-twitter"></i></a>
			</div>
			<a href="#" class="btn_contact">Contactez-nous</a>
		</div>
		
	
</footer>

</body>
</html>